yojuyoon/jwt_wechicken_frontend

src/Components/Nav.js, src/Components/ProfileIcon.js, src/Pages/MyGroup/Contributors/Contributor/Contributor.js, src/Pages/MyGroup/Contributors/Contributors.js, src/Pages/MyGroup/MyGroup.js, src/Routes.js
=> Add: MyGroup페이지 레이아웃

src/Components/Login/FormModal.js, src/Components/Login/GoogleLogin.js, src/Components/Nav.js, src/Pages/MyGroup/Contributors/Contributors.js, src/Pages/MyPage/MyPage.js, src/Pages/MyPage/MyPageContents/ProfileColumn.js, src/config.js, src/store/actions/loginAction.js, src/store/reducers/index.js, src/store/reducers/loginReducer.js, src/store/reducers/userProfileReducer.js
1)Reducer분리
2)리덕스 초기 값을 sessionStore에서 가져오게 설정
=> Refactor: Redux수정

src/Components/Buttons/BtnCheck.js, src/Components/Buttons/InputTheme.js, src/Components/Card/Card.js, src/Components/Login/FormModal.js, src/Components/Login/GoogleLogin.js, src/Components/Login/Login.js, src/Components/Login/LoginModal.js, src/Components/Login/LogoBox.js, src/Components/Nav.js, src/config.js
1)레이아웃 변경
2)필수 사항 미 입력시 예외처리 완료
=> Refactor: 최초 로그인 시, 추가 입력창 (FormModal)수정

src/Components/Login/GoogleLogin.js, src/Components/Login/LoginModal.js
1)회원가입 버튼 삭제
2)globalStyle -> background-color 추가 후 발생한 문제 해결
=> Refactor: 로그인 창 변경사항 반영

package-lock.json, package.json, src/Components/PostsOfTheWeek/MyGroupJoinModal.js, src/Components/PostsOfTheWeek/PostsOfTheWeek.js, src/Pages/MyGroup/Contributors/Contributor/Contributor.js, src/Pages/MyGroup/Contributors/Contributors.js, src/Pages/MyGroup/MyGroup.js, src/Styles/GlobalStyle.js, src/config.js
**[2020년 8월 31일]**
- 치킨계 미가입시 이주의 포스팅 열람 불가로 blur처리 및 Join버튼 활성화
- react-confirm-alert를 활용하여 confirm창 custom
- 가입 버튼 클릭 시 confirm창으로 확인 후 이주의 포스팅 열람 가능
=> Add: MyGroupJoin 버튼 활성화

src/Components/Buttons/HeartIcon.js, src/Components/Card/Card.js, src/Pages/Main/Main.js
1)백엔드 Api테스트
2)Main페이지 레이아웃 (MainContent & MainContentCards) padding 조정 및 스타일 추가
=> Add: Main페이지 내, Card 컴포넌트api연결

src/Components/Common/Error.js, src/Components/Nav.js, src/Pages/Main/Main.js, src/Pages/MyGroup/MyGroup.js, src/Pages/MyPage/MyPage.js, src/Routes.js, src/Styles/GlobalStyle.js
**[2020년 9월 1일]**
- Error창 구현
- Error 핸들링 필요한 부분에서 추후 적용할 예정
- GlobalStyle background-color 적용 취소 후 일부 리팩토링
=> Add: Error 창 구현 및 GlobalStyle 리팩토링

src/Components/Login/Login.js, src/Components/Nav.js, src/Components/PostsOfTheWeek/DayColumn.js, src/Components/PostsOfTheWeek/MiniPostCard.js, src/Components/PostsOfTheWeek/PostsOfTheWeek.js, src/Components/ProfileIcon.js, src/Pages/MyGroup/Contributors/Contributor/Contributor.js, src/Pages/MyGroup/Contributors/Contributors.js, src/Pages/MyGroup/MyGroup.js, src/Pages/MyPage/MyPage.js, src/Pages/MyPage/MyPageContents/ProfileColumn.js
1)Nav.js, ProfileColumn.js, Contributors.js에서 호출하는 ProfileIcon에 img데이터를 리덕스에서 받아오는 것으로 변경
2)마이페이지에서 이미지를 업로드 & 삭제할 경우 API호출이 정상일 경우, userProfileImg 액션 발행하는 것으로 변경 (리로드 삭제)
3)ProfileColumn에 있던 조건문 삭제
=> Refactor: ProfileIcon 컴포넌트 내부 및 호출하는 컴포넌트 코드 수정

public/index.html, src/Components/Buttons/InputTheme.js, src/Pages/MyGroup/CreateMyGroup/CreateMyGroup.js, src/Pages/MyGroup/CreateMyGroup/CreateMyGroupModal.js, src/Routes.js, src/Styles/GlobalStyle.js
**[2020년 9월 2일]**
- 내 기수 페이지 생성 창 레이아웃 구현
- 추후 백엔드와 통신 구현 예정
=> Add: 내 기수 페이지 생성창 레이아웃 구현 및 백엔드와 통신 구현 예정

src/Components/Common/Loading.js, src/Pages/Main/Main.js, src/Pages/MyGroup/MyGroup.js
=> Add: mygroup페이지 내 수동 크롤링 버튼(update)구현

src/Components/Card/Card.js, src/Components/Login/FormModal.js, src/Components/Login/Login.js, src/Pages/Main/Main.js, src/Pages/MyGroup/MyGroup.js, src/Pages/MyPage/MyPage.js, src/Pages/MyPage/MyPageContents/ContentsColumn.js, src/Pages/MyPage/MyPageContents/ProfileColumn.js, src/Pages/MyPage/MyPageContents/myPageContents.js, src/config.js, src/hooks/useUpload.js
1) 최초 로그인시, 추가 정보 기입란에서 치킨계 가입여부를 boolean 값으로 formData에 추가
2) 마이페이지의 회원 탈퇴 버튼을 치킨계 탈퇴로 변경
3) MyGroup페이지에서 이주의 공헌 카테고리 치킨계 가입여부에 따라 render여부 추가
=> Modify: Api호출 관련 및 레이아웃 수정

src/Components/Card/Card.js, src/Components/Nav.js, src/Pages/Liked/Liked.js, src/Pages/Main/Main.js, src/Routes.js, src/config.js
1)Liked페이지 기본 레이아웃
2)Nav 좋아요&북마크 아이콘 삭제 => 추후 dropdown메뉴에서 이동 할 수 있도록 추가
=> Add: Liked 페이지 레이아웃 완성

src/Components/Card/Card.js, src/Components/Dimmer.js, src/Components/Login/FormModal.js, src/Components/Nav.js, src/Pages/Liked/Liked.js, src/Pages/Main/Main.js, src/Pages/MyGroup/MyGroup.js, src/Pages/MyPage/MyPage.js, src/Pages/MyPage/MyPageContents/myPageContents.js, src/hooks/useUpload.js
1)Nav 드롭다운에 북마크 페이지 이동 카테고리 추가
2)*임시 Main페이지에 랜더되는 카드 컴포넌트의 데이터 랜덤 정렬 함수 추가
3)카드 컴포넌트 width 미디어 쿼리 추가
4)Dimmer 컴포넌트에 모달 활성화 시, 스크롤 방지 함수 추가
5)불필요한 콘솔 제거
=> Refactor: 메인 페이지 및 Dimmer창

src/Components/Login/GoogleLogin.js, src/Pages/MyGroup/CreateMyGroup/CelebratingModal.js, src/Pages/MyGroup/CreateMyGroup/CreateMyGroupModal.js, src/Pages/MyGroup/MyGroup.js, src/Routes.js
**[2020년 9월 4일]**
- 내 기수 페이지 생성 시 축하메세지 모달창 구현
=> Add: 내 기수 페이지 생성시 축하 모달창 구현

src/Components/Common/CelebratingModal.js, src/Components/Login/GoogleLogin.js, src/Components/Login/Login.js, src/Components/Login/LoginModal.js, src/Pages/MyGroup/CreateMyGroup/CreateOrModifyMyGroupModal.js, src/Pages/MyGroup/MyGroup.js
**[2020년 9월 7일]**
- 로그인 시 로딩창 핸들링(.then -> async/await로 변경)
=> Refactor: 로그인 시 로딩창 핸들링

src/Components/Buttons/Tag.js, src/Components/Card/Card.js, src/Components/Nav/DropDown.js, src/Components/Nav/Nav.js, src/Components/Nav/SearchBar.js, src/Pages/Liked/Liked.js, src/Pages/MyPage/MyPageContents/ContentsColumn.js, src/Routes.js
Add: Nav안 Search바 레이아웃 구현
Refactor: Nav&Licked
1)Nav 컴포넌트 분리(dropDown메뉴, search)
2)Liked페이지 active탭 상단 고정
=> Add: Nav안 Search바 레이아웃 구현

.eslintrc.json, src/Components/Alert.js, src/Components/Dimmer.js, src/Components/Login/FormModal.js, src/Components/Login/GoogleLogin.js, src/Components/Login/LoginModal.js, src/Components/Nav/Nav.js, src/Components/PostsOfTheWeek/DayColumn.js, src/Components/PostsOfTheWeek/MiniPostCard.js, src/Components/PostsOfTheWeek/MyGroupJoinModal.js, src/Components/PostsOfTheWeek/PostsOfTheWeek.js, src/Pages/Liked/Liked.js, src/Pages/MyGroup/MyGroup.js, src/Pages/MyPage/MyPage.js, src/Pages/MyPage/MyPageContents/ContentsColumn.js, src/Pages/MyPage/MyPageContents/ProfileColumn.js
**[2020년 9월 8일]**
- Alert 창 custom
=> Refactor: Alert custom 및 리팩토링

src/Components/PostsOfTheWeek/MyGroupJoinModal.js, src/Components/PostsOfTheWeek/PostsOfTheWeek.js, src/Pages/MyGroup/MyGroup.js
**[2020년 9월 8일]**
- 이주의 포스팅 Calendar 날짜 선택 시 백엔드 API호출 후 포스팅 업데이트
=> Add: Calendar 날짜 선택시 백엔드 API 호출 후 포스팅 업데이트

src/Components/Buttons/InputTheme.js, src/Components/Card/Card.js, src/Components/Nav/DropDown.js, src/Components/Nav/Nav.js, src/Components/Nav/SearchBar.js, src/Pages/Main/Main.js, src/Pages/Search/Search.js, src/Routes.js, src/store/actions/searchAction.js, src/store/reducers/index.js, src/store/reducers/searchReducer.js
1)search페이지에서 Throttling을 적용한 검색 Api호출
2)Nav의 search bar와 redux로 연결
=> Add: search 기능 구현

src/Components/PostsOfTheWeek/PostsOfTheWeek.js, src/Pages/Main/MainBannerContents.js, src/Pages/MyGroup/Contributors/Contributor/Contributor.js, src/Pages/MyGroup/Contributors/Contributors.js, src/Pages/MyPage/MyPageContents/ContentsColumn.js
**[2020년 9월 10일]**
- 이주의 공헌 페널티값 출력 디버깅 및 리팩토링
=> Refactor: MyGroup 페이지 이주의 공헌 디버깅 및 리팩토링

src/Components/Card/MiniCard.js, src/Pages/MyGroup/PostsOfTheWeek/DayColumn.js, src/Pages/MyGroup/PostsOfTheWeek/PostsOfTheWeek.js
media 쿼리 삭제
스크롤바 display : none
=> Fixed: media쿼리 수정, 스크롤바

src/Components/Card/Card.js, src/Pages/Main/Main.js, src/Pages/Main/MainBanner.js, src/Pages/MyGroup/MyGroupBanner.js
1. Main & MyGroup 페이지 상단 베너 넓이 퍼센트 
추가: 넓이 800px이하는 베너 사라지도록 설정
2. 로그인 전, 상단 베너 클릭시 로그인 alert 뜨도록 예외처리
3. 카드 컴포넌트 클릭 시, 새 창 열도록 수정
4. 검색 창에서 카드 컴포넌트 subtitle추가
=> Refactor: 피드백 반영 => Main, MainBanner, MyGroupBanner, Card 수정

src/Components/Card/Card.js, src/Pages/Search/Search.js
- search page: post 객체 내 subtitle 값이 없을 경우(ex. 미디엄) subtitle.length 등에서 에러를 내는 경우 옵셔널 체이닝으로 해결
- 검색어 유무 등에 따른 안내메시지 표시 (검색 키워드 입력, 검색 결과가 없습니다)
=> Fix: search subtitle null 에러 수정, 검색 키워드 상태에 따른 안내 메시지 처리

src/Components/Buttons/BtnTheme.js, src/Components/Card/MiniCard.js, src/Pages/MyGroup/MyGroup.js, src/Pages/Search/Search.js
-미니 카드 컴포넌트 새탭으로 열기
-임시: velog 유저도 포스팅 추가 버튼
=> Refactor: 마이그룹페이지 임시 수정

src/Components/Buttons/BtnTheme.js, src/Pages/MyGroup/Contributors/Contributors.js, src/Pages/MyGroup/MyGroup.js, src/Styles/Theme.js
- myGroup 페이지 컴포넌트 width 일괄 수정
=> Refactor: MyGroup css 수정

src/Pages/MyGroup/MyGroup.js, src/Pages/MyGroup/MyGroupBanner.js
- 내 기수 페이지 이주의 포스팅 하당 margin-bottom 속성 추가
- Banner 반응형 수정
=> Refactor: 내 기수 페이지 UI 일부 수정

src/Components/Nav/SearchBar.js, src/Pages/Main/Main.js, src/Pages/MyPage/MyPageContents/Components/MyPostEditModal.js, src/Pages/MyPage/MyPageContents/MyPosts.js, src/Pages/Search/Search.js, src/config.js, src/constants.js, src/hooks/usePagination.js
**[검색 페이지 Pagination 기능 추가]**
- 키워드 변경 시 posts 배열 초기화 및 window.scrollToTop(0, 0) 적용
- usePagination에서 setPage return 배열에 추가 한 뒤 검색페이지에서 keyword변경 시 page값 초기화
**[검색 페이지 UI 보완]**
- 검색페이지 SearchWrap fixed 적용
**[리팩토링]**
- ref 변수명 분명한 변수명으로 수정
- pagination limit 값 상수 파일 분리 후 import
=> Add: 검색 페이지 Pagination 기능 추가
